- shortcode/posts.php
> Added Posts shortcode

- admin/static/js/rules.js
Issue: https://github.com/bagrinsergiu/blox-editor/issues/3395
> Conflict with global vars windows Select2 between plugins

- admin/rules/api.php
- admin/rules/manager.php
- admin/templates.php
Related issue: https://github.com/ThemeFuse/Brizy/issues/728
> The check for rules on restore post

- compatibilities/gutenberg.php
Issue: https://github.com/ThemeFuse/Brizy/issues/902
> Remove wpautop filter

- brizy.php
- compatibilities/init.php
- compatibilities/phastpress.php
- editor.php
1. Load compatibilities earlier and separate them at the main brizy loader.
2. Add compatibility with PhastPress plugin
> Separate the load compatibilities, add compatibility with phastpress

- admin/popups/main.php
- admin/rules/manager.php
Changed the matching popup code.
Issue: #7637
> Compile popup before inserting in page.

- editor/editor/editor.php
> FIxed the post chace id when the config is build without post

- editor.php
- shortcode/woo-product-page-wrapper.php
- tests/functional/ShortCodeWooProducPageWrapperCest.php
It accepts id as an attribute.
If no attribute is provided it will try to take the product from globals.
If no product is found in globals it will take a random product.
#7657
> Added a wrapper shortcode for product_page whortcode from woocomerce.

- compatibilities/yoast-seo.php
- public/main.php
Bucata asta de cod e foarte sensibila.
Trebuei de vazut daca nu am scapat ceva din vedere.
> Compatibility fix for Happy Form + Yoast SEO + Brizy

- admin/form-entries.php
Fix: https://github.com/ThemeFuse/Brizy/issues/1514
> Issue #1514 - Use htmlentities on each name and value of the form fields

- admin/templates.php
- public/main.php
* Fixed: Errors in js from the theme or other plugins preventing our js to work properly
> changed preview init to happen on DOMContentLoaded

- public/main.php
Added possibility to add dependencies to `preview.js`
> added brizy_preview_js_deps filter

- editor.php
[Issue](https://github.com/bagrinsergiu/blox-editor/issues/12438)
> issue #12438 - rewrite nr. of revisions if it is -1

- editor/post.php
https://github.com/bagrinsergiu/blox-editor/issues/13088
> Added post_status in brizy_get_posts  actions

- admin/popups/main.php
https://github.com/bagrinsergiu/blox-editor/issues/13054
> Fixed  exclusion rules for popups

- content/providers/free-provider.php
https://github.com/bagrinsergiu/blox-editor/issues/13264
> #13264 - dynamic content in membership block

- admin/settings.php
- compatibilities/bbpress.php
- compatibilities/init.php
https://github.com/bagrinsergiu/blox-editor/issues/12941
> Compatibility with bbpress plugin

- editor/post.php
https://github.com/bagrinsergiu/blox-editor/issues/13348
> #13391 - display posts to template conditions

- compatibilities/init.php
- compatibilities/tfuse.php
https://github.com/bagrinsergiu/blox-editor/issues/12569
> #12569 - compatibility with themefuse old themes

- admin/blocks/api.php
- admin/entity/abstract-manager.php
- editor/editor/editor.php
https://github.com/bagrinsergiu/blox-editor/issues/13307#event-4374928154
> #13307 - Avoid duplicate global blocks on create blocks

- content/providers/abstract-provider.php
- content/providers/free-provider.php
- public/main.php
[Related pr from pro](https://github.com/bagrinsergiu/Brizy-Pro/pull/48)
https://github.com/bagrinsergiu/blox-editor/issues/12720
> #12720 - add script dependencies from placeholder

- admin/rules/manager.php
https://github.com/bagrinsergiu/blox-editor/issues/12838
> #12838 - page shop as front page template issue

- editor.php
- tests/functional/Brizy_EditorCest.php
[Issue](https://github.com/bagrinsergiu/blox-editor/issues/13113)
It is related to this pr in pro: https://github.com/bagrinsergiu/Brizy-Pro/pull/47
> #13113 - white label prefix in the multisite

- editor/crop-cache-media.php
- public/crop-proxy.php
https://github.com/bagrinsergiu/blox-editor/issues/13119
> #13119 - possibility to crop image by its dynamic url

- languages/brizy.pot
https://github.com/bagrinsergiu/blox-editor/issues/13297
> #13297 - updated .pot file

- admin/rules/api.php
https://github.com/bagrinsergiu/blox-editor/issues/13493
> fix: remove product_visibility taxonomy form template conditions

- admin/main.php
- admin/static/js/featured-image.js
https://github.com/bagrinsergiu/blox-editor/issues/10631
> fix: save focal point on save post

- public/main.php
https://github.com/bagrinsergiu/blox-editor/issues/13604
> fix: Sorry, Brizy could not load the_content on blog page

- admin/templates.php
- public/main.php
- public/views/templates/brizy-blank-template.php
- public/views/templates/brizy-header-footer-template.php
https://github.com/bagrinsergiu/blox-editor/issues/13586
> Fix password protected through templates

- admin/main.php
- admin/views/button.php
https://github.com/bagrinsergiu/blox-editor/issues/13618
> fix: Do not translate Company Name when there's white label

- content/providers/free-provider.php
related issue https://github.com/bagrinsergiu/blox-editor/issues/13639
> Fixed category not working for editor_product_products

- admin/form-entries.php
https://github.com/bagrinsergiu/blox-editor/issues/1514
> fix: encode and decode leads with utf-8

- content/providers/free-provider.php
- languages/brizy.pot
- public/views/post-info.html.twig
https://github.com/bagrinsergiu/blox-editor/issues/13774
> fix: updated translates

- public/main.php
https://github.com/bagrinsergiu/blox-editor/issues/13761
> fix: hide pages with status draft for non logged users

- admin/form-entries.php
- admin/popups/main.php
- admin/stories/main.php
- languages/brizy.pot
https://github.com/bagrinsergiu/blox-editor/issues/14000
> fix: added some strings to the .pot file

- compatibilities/yoast-seo.php
- content/main-processor.php
https://github.com/bagrinsergiu/blox-editor/issues/13746
> fix: don't run html_entity_decode over the post content

- admin/migrations/fix-globals-to-data-migration.php
- admin/migrations/posts-trait.php
- editor.php
- editor/project.php
https://github.com/bagrinsergiu/blox-editor/issues/13654
> fix: do not run migrations until project data is created

- admin/rule.php
- admin/rules/manager.php
> fix: Template rule match for product archive matches all archives

- admin/form-entries.php
https://github.com/bagrinsergiu/blox-editor/issues/14089
> fix: WhiteLabel option: LEADS are not displayed in the menu settings

- editor.php
https://github.com/bagrinsergiu/blox-editor/issues/14382
> Uncommented story in WP

- compatibilities/init.php
- compatibilities/the-events-calendar.php
https://github.com/bagrinsergiu/blox-editor/issues/14339
> fix: Compatibility The Events Calendar plugin

- admin/settings.php
- admin/views/settings/general.php
- brizy.php
- update.php
Postpone update for the beta release
> postpone update

- public/main.php
https://github.com/bagrinsergiu/blox-editor/issues/14467
> fix: apply filters the_content on shop page edited with editor

- editor/editor/editor.php
https://github.com/bagrinsergiu/blox-editor/issues/13285
> fix: Membership View as Roles Order

- brizy.php
- compatibilities/brizy-pro-compatibility.php
- compatibilities/init.php
> Fix: stop running pro if versions are not good

- editor/editor/editor.php
need to merge only when this issue is closed https://github.com/bagrinsergiu/blox-editor/issues/14491
> Config branding->brizy to branding->name

- admin/cloud/font-bridge.php
- editor/asset/static-file-trait.php
- editor/screenshot/manager.php
- editor/zip/archiver.php
- public/asset-proxy.php
issue: https://github.com/bagrinsergiu/blox-editor/issues/15623
> fix: Use Brizy_Public_AssetProxy::get_mime instead of native function

- brizy.php
- editor.php
- system-checks.php
> new: Added extension presence check at the start of the plugin

- editor/asset/crop/wordpress-service.php
> fix: floor the size values that are passed to the cropper

- admin/membership/membership.php
- content/providers/free-provider.php
- editor.php
> Membership improvments

- compatibilities/translate-press.php
- editor/editor/editor.php
#15575, #16163, #16015, #16281
[ skip ci ]
> Fix: #16163 - Improvement menu

- public/views/page.html.twig
issue: [#16367](https://github.com/bagrinsergiu/blox-editor/issues/16367)
> new: html changes in page.html.twig

- admin/templates.php
- compatibilities/woocommerce.php
Fix: #16378 - Show woo notices on templates for products
> Fix: #16378 - Show woo notices on templates for products

- admin/blocks/api.php
- admin/entity/abstract-manager.php
- admin/layouts/api.php
- editor/block.php
- editor/entity.php
- editor/layout.php
- editor/popup.php
- editor/post-tags-aware.php
- editor/post.php
- editor/zip/archiver.php
Added title and tags for block/layouts/popups
> new: Added title and tags for block/layouts/popups

- content/placeholders/ignore-dc.php
- content/providers/free-provider.php
> new: Added ignore dc placeholder

- config.dev.php
- config.php
- editor/editor/editor.php
- editor/post.php
- editor/url-builder.php
- public/asset-enqueue-manager.php
- site-url-replacer.php
https://github.com/bagrinsergiu/blox-editor/issues/17411
> Fix: #17411 - saves scripts relative to the plugin main folder

- admin/blocks/api.php
- admin/blocks/manager.php
- admin/entity/abstract-manager.php
- editor/block.php
https://github.com/bagrinsergiu/blox-editor/issues/17618
> Fix: #17618 - optimize save global blocks on save page

- admin/form-entries.php
- admin/migrations.php
- admin/migrations/change-post-types-names.php
- admin/popups/main.php
- admin/rules/api.php
- admin/templates.php
- tests/acceptance/PopupDefaultRulesCest.php
- tests/functional/ApiCest.php
- tests/functional/PopupsMainCest.php
- tests/unit/BrizyAdminRuleTest.php
- tests/unit/BrizyCompatibilitiesSeoPressTest.php
https://github.com/bagrinsergiu/blox-editor/issues/18485
> Fix: #18485 - Prefix brizy post types names with a generic one

- admin/rules/api.php
The Brizy Templates must not be shown as a rule option for popups
issue: #18944
> Global block context

- editor/api.php
> fix: Dynamic fields in templates

- public/editor-client/src/index.ts
- public/editor-client/src/media/addMediaGallery.ts
- public/editor-client/src/media/utils.ts
- public/editor-client/src/types/Media.ts
- public/editor-client/src/types/global.d.ts
Related to : https://github.com/bagrinsergiu/blox-editor/issues/22128
> moved galleryMedia to api

- editor/editor/editor.php
Added default values for editor components
issue: https://github.com/bagrinsergiu/Brizy-Cloud/issues/3198
> Issue 3198: Added default values for editor components

- editor/editor/editor.php
- editor/editor/module-groups/archive-provider.php
- editor/editor/module-groups/content-provider.php
- editor/editor/module-groups/context-utils.php
- editor/editor/module-groups/essential-provider.php
- editor/editor/module-groups/grid-provider.php
- editor/editor/module-groups/manager.php
- editor/editor/module-groups/media-provider.php
- editor/editor/module-groups/module-group.php
- editor/editor/module-groups/product-provider.php
- editor/editor/module-groups/provider-interface.php
- editor/editor/module-groups/single-provider.php
- editor/editor/module-groups/social-provider.php
- editor/editor/module-groups/story-provider.php
- editor/editor/module-groups/wordpress-provider.php
https://github.com/bagrinsergiu/blox-editor/issues/22402
> WP : ModulesGroups key to config

- admin/blocks/api.php
- admin/layouts/api.php
- editor/zip/archiver.php
issue: [#22540](https://github.com/bagrinsergiu/blox-editor/issues/22540)
> fix: rremove the sufix from version compare when importing from zip

- brizy.php
- editor/editor/editor.php
> new: Add ui config

- compatibilities/translate-press.php
https://github.com/bagrinsergiu/blox-editor/issues/22000
> translatepress incompatibility solved

- editor/editor/editor.php
issue: https://github.com/bagrinsergiu/blox-editor/issues/22812
> fix: Sidebar config

- editor/editor/editor.php
https://github.com/bagrinsergiu/blox-editor/issues/22933
> fix: Remove delete button for internal popups

- editor/editor/editor.php
issue: https://github.com/bagrinsergiu/Brizy-Cloud/issues/3320
> new: Added placeholder for PostTitle and PostContent

- editor/editor/editor.php
- editor/post.php
issue: https://github.com/bagrinsergiu/blox-editor/issues/22986
> new: added page data in editor config

- editor/editor/module-groups/archive-provider.php
- editor/editor/module-groups/content-provider.php
- editor/editor/module-groups/essential-provider.php
- editor/editor/module-groups/grid-provider.php
- editor/editor/module-groups/manager.php
- editor/editor/module-groups/media-provider.php
- editor/editor/module-groups/module-group.php
- editor/editor/module-groups/product-provider.php
- editor/editor/module-groups/single-provider.php
- editor/editor/module-groups/social-provider.php
- editor/editor/module-groups/story-provider.php
- editor/editor/module-groups/woo-archive-provider.php
- editor/editor/module-groups/wordpress-provider.php
Added sorting groups by priority in the editor
> Issues#22955 - Added sorting groups by priority in the editor

- public/editor-client/src/customFile/addFile.ts
- public/editor-client/src/types/global.d.ts
issue link --> https://github.com/bagrinsergiu/blox-editor/issues/23043
> feat(image-upload): added all type files

- public/editor-client/src/config.ts
- public/editor-client/src/defaultTemplates/index.ts
- public/editor-client/src/index.ts
- public/editor-client/src/types/DefaultTemplate.ts
- public/editor-client/src/types/global.d.ts
Related Tickets https://github.com/bagrinsergiu/blox-editor/issues/22442
> add default templates in wp-plugin

- public/editor-client/src/customFile/addFile.ts
- public/editor-client/src/types/global.d.ts
issue link --> https://github.com/bagrinsergiu/blox-editor/issues/23043
> feat(image-upload): beta - added all type files

- public/editor-client/src/savedBlocks/savedPopups.ts
Related to : https://github.com/bagrinsergiu/blox-editor/issues/23302
[beforePopupList.webm](https://github.com/ThemeFuse/Brizy/assets/40203375/63edeec5-186a-491a-8f04-9edb6a5d4fc2)
[afterPopupList.webm](https://github.com/ThemeFuse/Brizy/assets/40203375/de3b1d52-9b15-4f4d-8fe3-89dc3f52775f)
> fix(savedPopups) :  Popup list infinite requests

- public/editor-client/src/api/adapter.ts
https://github.com/bagrinsergiu/blox-editor/issues/23407
> refactor(edit): edit tags

- public/editor-client/src/types/global.d.ts
issue --> https://github.com/bagrinsergiu/blox-editor/issues/23396
> resolve tsc tests from file upload type

- public/editor-client/src/api/index.ts
> fix(api): send correct request

- public/editor-client/src/api/index.ts
- public/editor-client/src/collectionItems/getCollectionItemsIds.ts
- public/editor-client/src/dynamicContent/utils.ts
- public/editor-client/src/types/global.d.ts
Was added `makePlaceholder` and `explodePlaceholder` handlers in api-client
> feat(editor-client): dynamic content handlers

- public/views/page.php
| Q  | A |
| ------------- | ------------- |
| Screenshot  | ![Screenshot from 2023-08-04 15-25-09](https://github.com/ThemeFuse/Brizy/assets/40203375/6a40258e-32b8-42f9-b136-ac52f74ecf50) |
| Related tickets	  |  https://github.com/bagrinsergiu/blox-editor/issues/23521   |
* Fixed: Added outdated safari version notification when editor loads
> fix: Added outdated safari notification

- public/editor-client/src/media/addMedia.ts
- public/editor-client/src/media/addMediaGallery.ts
Fixed infinite loading and added a toast notification when closing a wordpress image gallery popup
Video: https://jmp.sh/r1eZ5LPW
> 23073 - infinite loading on close image gallery

- editor/editor/editor.php
- public/editor-client/package-lock.json
- public/editor-client/package.json
- public/editor-client/src/Elements/Posts/index.ts
- public/editor-client/src/index.ts
- public/editor-client/src/types/Collections.ts
- public/editor-client/src/types/Posts.ts
- public/editor-client/src/types/global.d.ts
- public/main.php
Related ticket https://github.com/bagrinsergiu/blox-editor/issues/23303
> Added elements to editor-client

- public/editor-client/src/Elements/Filters/index.ts
- public/editor-client/src/Elements/Filters/utils.ts
- public/editor-client/src/api/index.ts
- public/editor-client/src/config.ts
- public/editor-client/src/index.ts
- public/editor-client/src/types/Filters.ts
- public/editor-client/src/types/global.d.ts
- public/editor-client/src/utils/reader/array.ts
Filters Sources from API
related issue: https://github.com/bagrinsergiu/blox-editor/issues/24162
> Filters From Api

- public/editor-client/src/aiText/index.ts
- public/editor-client/src/config.ts
- public/editor-client/src/index.ts
- public/editor-client/src/types/AiText.ts
- public/editor-client/src/types/global.d.ts
API-Client for AI-Text Wordpress
> feat(ai): ai-text wp

- public/editor-client/src/Elements/Posts/index.ts
- public/editor-client/src/types/Posts.ts
Related issue https://github.com/bagrinsergiu/blox-editor/issues/24388
> hotfix orderBy

- public/editor-client/src/aiText/index.ts
- public/editor-client/src/config.ts
- public/editor-client/src/index.ts
- public/editor-client/src/types/global.d.ts
> 24429 api url

- public/editor-client/src/aiText/index.ts
- public/editor-client/src/types/AiText.ts
Changed model from gpt-3.5-turbo to gpt-3.5-turbo-1106 (response speed decreased from average 30-40 seconds to average 4-8 seconds)
> perf(api-aitext): changed GPT model to gpt-3.5-turbo-1106

- public/editor-client/package-lock.json
- public/editor-client/package.json
- public/editor-client/src/aiText/index.ts
- public/editor-client/src/aiText/utils.ts
- public/editor-client/src/types/AiText.ts
*Improve: Changed instructions, so response from AI become more correctly
> Refactor AI-Text API

- admin/layouts/api.php
- editor/layout.php
- editor/zip/archiver.php
- public/editor-client/src/api/adapter.ts
- public/editor-client/src/api/index.ts
- public/editor-client/src/types/SavedBlocks.ts
> Added layout with globalStyles

- public/editor-client/src/defaultTemplates/index.ts
- public/editor-client/src/defaultTemplates/tempComverters.ts
- public/editor-client/src/defaultTemplates/utils.ts
- public/editor-client/src/types/DefaultTemplate.ts
- public/editor-client/src/types/global.d.ts
Related issue https://github.com/bagrinsergiu/blox-editor/issues/25306
> Kits from API

- public/editor-client/src/defaultTemplates/tempComverters.ts
Related issue https://github.com/bagrinsergiu/blox-editor/issues/25519
> kit1 blank

- editor/editor/editor.php
Issue: https://github.com/bagrinsergiu/blox-editor/issues/25590
> refactor(config): rename form keys, and add showIntegrations

- editor/editor/editor.php
Issue: https://github.com/bagrinsergiu/blox-editor/issues/25611
> refactor(config): remove multilanguage key, and add membership

- editor/editor/editor.php
- public/editor-client/package-lock.json
- public/editor-client/package.json
- public/editor-client/src/api/index.ts
- public/editor-client/src/config.ts
- public/editor-client/src/index.ts
- public/editor-client/src/onStartLoad/index.ts
- public/editor-client/src/types/global.d.ts
Issue: https://github.com/bagrinsergiu/blox-editor/issues/25595
> feat(api): move lock/unlock to api client

- public/editor-client/src/api/index.ts
- public/editor-client/src/api/types.ts
- public/editor-client/src/config.ts
- public/editor-client/src/heartBeat/index.ts
- public/editor-client/src/index.ts
- public/editor-client/src/types/global.d.ts
Issue : https://github.com/bagrinsergiu/blox-editor/issues/25717
> feat(wp api client): move heartBeat to api client

- public/editor-client/src/utils/createUpload.ts
| Q  | A |
| ------------- | ------------- |
| Screenshot  | N/A |
| Related tickets	  | https://github.com/bagrinsergiu/Brizy-Cloud/issues/3576  |
* Fixed: Text space for ordered and unordered lists
> fix(fileUpload): file upload cancelled 

- public/editor-client/src/api/index.ts
- public/editor-client/src/config.ts
- public/editor-client/src/fonts/index.ts
- public/editor-client/src/index.ts
- public/editor-client/src/types/global.d.ts
Issue: https://github.com/bagrinsergiu/blox-editor/issues/25812
> move getUploadedFonts to wp ApiClient

- public/editor-client/src/config.ts
- public/editor-client/src/index.ts
- public/editor-client/src/types/global.d.ts
> refactor(api): imagePatterns

- public/editor-client/src/api/index.ts
- public/editor-client/src/config.ts
- public/editor-client/src/customIcon/index.ts
- public/editor-client/src/customIcon/utils.ts
- public/editor-client/src/index.ts
- public/editor-client/src/types/Icon.ts
- public/editor-client/src/utils/base64.ts
- public/editor-client/src/utils/uploadFile.ts
> Added custom icons in editor

- editor/trait/sanitize.php
[bagrinsergiu/blox-editor/issues/25738](https://github.com/bagrinsergiu/blox-editor/issues/25738)
> Sanitize attributes

- config.dev.php
- config.php
- editor/editor/editor.php
- public/editor-client/src/api/index.ts
- public/editor-client/src/config.ts
- public/editor-client/src/defaultTemplates/index.ts
- public/editor-client/src/defaultTemplates/utils.ts
- public/editor-client/src/types/DefaultTemplate.ts
Related issue: https://github.com/bagrinsergiu/blox-editor/issues/25612
> wp popups beta

- config.dev.php
- config.php
- editor/editor/editor.php
- public/editor-client/src/config.ts
Related issue: https://github.com/bagrinsergiu/blox-editor/issues/26737
> Removed unused vars from Default Templates

- public/editor-client/src/defaultTemplates/utils.ts
- public/editor-client/src/types/DefaultTemplate.ts
Related issue: https://github.com/bagrinsergiu/blox-editor/issues/27830
> removed icon

- public/editor-client/src/defaultTemplates/utils.ts
Related issue: https://github.com/bagrinsergiu/MB-Support/issues/560
> Temp Urls for Layouts and Blocks

- public/editor-client/src/api/index.ts
- public/editor-client/src/config.ts
- public/editor-client/src/index.ts
- public/editor-client/src/menu/index.ts
- public/editor-client/src/menu/types.ts
- public/editor-client/src/types/global.d.ts
Related issue: https://github.com/bagrinsergiu/blox-editor/issues/28258
> api for menus

- public/editor-client/src/api/index.ts
- public/editor-client/src/config.ts
- public/editor-client/src/index.ts
- public/editor-client/src/shortcodeContent/index.ts
- public/editor-client/src/shortcodeContent/types.ts
Related issue: https://github.com/bagrinsergiu/blox-editor/issues/28287
> API requests for shortcodeContent

- public/editor-client/package-lock.json
- public/editor-client/package.json
- public/editor-client/src/api/index.ts
- public/editor-client/src/authors/index.ts
- public/editor-client/src/authors/types.ts
- public/editor-client/src/config.ts
- public/editor-client/src/index.ts
Related issue: https://github.com/bagrinsergiu/blox-editor/issues/28311
> getAuthors API

- public/editor-client/src/api/index.ts
- public/editor-client/src/config.ts
- public/editor-client/src/index.ts
- public/editor-client/src/sidebars/index.ts
- public/editor-client/src/sidebars/types.ts
Related issue: https://github.com/bagrinsergiu/blox-editor/issues/28310
> API for getSidebars request

- parser/dom-document.php
https://github.com/bagrinsergiu/blox-editor/issues/27014
> Fix DOMDocument encoding and suppress HTML parsing errors

- content/placeholders/image-attribute.php
https://github.com/bagrinsergiu/blox-editor/issues/28242
> Issue28242

- content/placeholders/image-attribute.php
https://github.com/bagrinsergiu/blox-editor/issues/28242#issuecomment-2717916117
> Issue28242_2

- editor/editor/editor.php
https://github.com/bagrinsergiu/blox-editor/issues/27716
> Update media URL generation to handle query parameter presence

- compatibilities/init.php
- compatibilities/squirrly-seo.php
https://github.com/bagrinsergiu/blox-editor/issues/28484
> Add compatibility with Squirrly SEO plugin

- editor/editor/editor.php
https://github.com/bagrinsergiu/blox-editor/issues/28555
> added isRTL key in config

- compatibilities/translate-press.php
https://github.com/bagrinsergiu/blox-editor/issues/28439
https://github.com/bagrinsergiu/blox-editor/issues/11991
> Fix double slashes in URLs for consistent formatting

- editor/editor/editor.php
https://github.com/bagrinsergiu/blox-editor/issues/28570
> Implement editor URL generation for Brizy-enabled menu items

- editor/editor/editor.php
https://github.com/bagrinsergiu/blox-editor/issues/28720
> additional action keys in __BRZ_PLUGIN__ENV

- editor/editor/editor.php
https://github.com/bagrinsergiu/blox-editor/issues/28833
> Refactor editor API actions setup

- compatibilities/wp-optimize.php
https://github.com/bagrinsergiu/blox-editor/issues/29411
> fix: wp-optimize exclude js, async css brz min files
