ThemeFuse/Brizy

editor/asset/media-asset-processor.php
Some themes/plugins adds function like this to parse_query:
```
function my_files_only( $wp_query ) {
if ( $wp_query->query_vars['post_type'] == "attachment" ) {
if ( ! current_user_can( 'level_5' ) ) {
global $current_user;
$wp_query->set( 'author', $current_user->id );
}
}
}
add_filter( 'parse_query', 'my_files_only' );
```
That means when the attachment is extracted from db in the query vars is inserted one more var in the case above by author ```$wp_query->set( 'author', $current_user->id );```; but this attachment can be added by other user and it will not be get form db.
=> Jump over parse_query hooks

public/main.php
I don't see a better way to solve it. Maybe it might be good to create a class to load it only in edit mode with fixes coming from other plugins.
=> Conflict with plugin wp-copyright-protection

editor/content/content-processor.php, editor/content/processor-interface.php, editor/post.php, public/main.php
There are many themes using mutiple times of the hook the_content for example this theme: https://themeforest.net/item/april-wonderful-fashion-woocommerce-wordpress-theme/20647488?s_rank=1
They extract some content from theme options for header/footer and apply filters on it, one of them is the the_content so when we are in a page buildin with brizy the content of the builder is showing for each apply filter the_content.
Related issue: https://github.com/bagrinsergiu/blox-editor/issues/3305
=> Don't insert builder content on each execution of the hook the_content

editor/asset/static-file.php, public/asset-proxy.php
There are conflicts with some cache plugins: wp rocket plugin, w3 total cache.
=> Remove content length header

editor/asset/media-asset-processor.php
When you migrate the site from http to https the home_url() returns the url with https but in the saved content the urls remain with http and the regex can't find them to replace with the static path file.
=> Migration the site http to https

compatibilities/autoptimize.php
When Brizy editor doesn't support this post type that we get by: ```Brizy_Editor_Post::get( $pid )``` it is getting an exception triggered in the function ```checkIfPostTypeIsSupported```
=> enable autoptimize_filter_js_noptimize only by GET key iframe

public/main.php, public/views/page.html.twig, public/views/templates/brizy-blank-template.php, public/views/templates/brizy-template.php
When the theme doesn't support ```title-tag``` and the user uses the template ```Brizy Template``` then we don't have any title tag for the browser tab.
Some old themes have an old implementation of the tag title. They have in the header.php something like that: ```<title><?php wp_title( '|', true, 'right' ); ?></title>```.
Since wordpress 4.1 theme authors must use something like that:
```
function theme_slug_setup() {
add_theme_support( 'title-tag' );
}
add_action( 'after_setup_theme', 'theme_slug_setup' );
```
but not all theme moved their themes to the new version so when is ```Brizy Template``` we don't have tag title because we don't use header.php of the theme.
Further information:
https://make.wordpress.org/core/2014/10/29/title-tags-in-4-1/
=> Browser tab title

editor/block-screenshot-api.php
[An anti-malware plugin](https://wordpress.org/plugins/gotmls/) was preventing the correct functioning of our block screenshots. This addresses the issue by renaming the api parameter that holds the screenshot image
=> fixed conflict with anti-malware plugin

editor.php, editor/editor/editor.php, editor/post.php
If there is a template added for only post type page when we get it for every post we edit with brizy. For example, if I have a template added only for pages:
```
/**
* Template Name: Visual Builder Template
*/
```
then I edit an article(post type post) with brizy and choose this template it won't save.
This pr will pull only templates added for the current editing post's post type.
=> Get templates depending on the post type

composer.json, composer.lock
By default composer 2.0 does check all platform requirements defined in composer.json. More info: https://php.watch/articles/composer-platform-check and https://stackoverflow.com/questions/26277151/force-composer-to-require-php-version-between-version-x-and-version-y/55698357
Issue: https://github.com/bagrinsergiu/blox-editor/issues/13056
=> fix: Disabled composer platform check

compatibilities/woocommerce.php, parser/dom-node.php, parser/pquery.php
https://github.com/bagrinsergiu/blox-editor/issues/16581
=> Fix: #16581 - extend pQuery to not use html_entity_decode

brizy.php
https://developer.wordpress.org/plugins/internationalization/how-to-internationalize-your-plugin/#plugins-on-wordpress-org
=> Fix: #18190 - Plugin is not compatible with language packs wordpress.org

editor/editor/editor.php, public/editor-client/src/api/index.ts, public/editor-client/src/config.ts, public/editor-client/src/customFile/addFile.ts, public/editor-client/src/index.ts, public/editor-client/src/types/File.ts, public/editor-client/src/types/global.d.ts
Related to : https://github.com/bagrinsergiu/blox-editor/issues/22182
=> moved api for FileUpload

public/editor-client/src/api/index.ts
Related to https://github.com/bagrinsergiu/blox-editor/issues/23277
[wordressRemoveTag.webm](https://github.com/ThemeFuse/Brizy/assets/40203375/104474a5-4762-4dd5-a923-b207db34353b)
[afterWPTagRemove.webm](https://github.com/ThemeFuse/Brizy/assets/40203375/a4267d94-16e2-4c7b-a00e-2cdad69a895d)
=> fix(api-client) : Saved block tag not removing

public/editor-client/src/api/types.ts, public/editor-client/src/api/utils.ts, public/editor-client/src/savedBlocks/savedBlocks.ts, public/editor-client/src/savedBlocks/savedLayouts.ts, public/editor-client/src/savedBlocks/savedPopups.ts
| Q  | A |
| ------------- | ------------- |
| Screenshot  | N/A |
| Related tickets	  | https://github.com/bagrinsergiu/Brizy-Cloud/issues/3735 |
[beforeWPBlockImport.webm](https://github.com/ThemeFuse/Brizy/assets/40203375/03f45c5e-eb2a-4d3d-81c7-fb66088d3b4f)
[afterWPBlockImport.webm](https://github.com/ThemeFuse/Brizy/assets/40203375/817e2f6a-3711-45b4-b63b-0c1c2aadb5e8)
* Improved: Explicit error messages for saved blocks import
=> refactor(apiSavedBlocks) : added explicit error messages for saved blocks import

public/editor-client/src/savedBlocks/savedBlocks.ts, public/editor-client/src/savedBlocks/savedLayouts.ts, public/editor-client/src/savedBlocks/savedPopups.ts
| Q  | A |
| ------------- | ------------- |
| Screenshot  |  ![image](https://github.com/bagrinsergiu/blox-editor/assets/40203375/f32261a2-fabe-4402-a0ab-6f251186acd0) |
| Related tickets	  | https://github.com/bagrinsergiu/blox-editor/issues/24395 |
Changed to descending order based on this comment : 
* Refactor: Descending order for saved blocks
=> refactor(apiSavedBlocks) :  changed to descending order for saved blocks

config.dev.php, config.php, editor/editor/editor.php, public/editor-client/src/api/index.ts, public/editor-client/src/config.ts, public/editor-client/src/index.ts, public/editor-client/src/regeneratedGlobalStyles/index.ts, public/editor-client/src/types/DefaultTemplate.ts
Related issue https://github.com/bagrinsergiu/blox-editor/issues/25691
=> WP Ai Global Styles

public/editor-client/src/media/addMedia.ts, public/editor-client/src/media/addMediaGallery.ts
Related issue: https://github.com/bagrinsergiu/blox-editor/issues/26953
=> Image id fixes for request

compatibilities/init.php, compatibilities/seo-press.php, editor/trait/sanitize.php
Added a method to clean up placeholder tags from Brizy global blocks in SEO Press meta descriptions. This ensures cleaner and more accurate meta data for improved SEO performance.
=> Remove Brizy global block placeholders in SEO Press titles

import/cleaner.php
Added a new condition to exclude 'wpcode' post type from deletion in the database cleanup query. This ensures better compatibility and prevents unintended removal of relevant data. Adjusted code formatting for consistency and readability. https://github.com/bagrinsergiu/blox-editor/issues/25526
=> Enhance data cleanup logic in cleaner.php
